<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dotnet10Server</RootNamespace>
    <AssemblyName>dotnet10-server</AssemblyName>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <PublishAot Condition="'$(PublishAot)' == ''">false</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <OptimizationPreference>Speed</OptimizationPreference>
    <DefineConstants>$(DefineConstants);NATIVE_AOT</DefineConstants>
  </PropertyGroup>

</Project>
